"""empty message

Revision ID: 1c45916ce45d
Revises: cb875229c098
Create Date: 2024-01-18 12:54:24.469562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c45916ce45d'
down_revision = 'cb875229c098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('donate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donate_amt', sa.Float(), nullable=False),
    sa.Column('donate_userid', sa.Integer(), nullable=True),
    sa.Column('donate_date', sa.DateTime(), nullable=True),
    sa.Column('donate_status', sa.Enum('pending', 'paid', 'failed'), nullable=True),
    sa.Column('donate_donor', sa.String(length=200), nullable=True),
    sa.Column('donate_email', sa.String(length=120), nullable=True),
    sa.Column('donate_ref', sa.String(length=200), nullable=True),
    sa.Column('donate_paygate', sa.String(length=200), nullable=True),
    sa.Column('donate_dateupdated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donate_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('donate_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_doname', sa.String(length=20), nullable=True))
        batch_op.drop_column('admin_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_username', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('admin_doname')

    op.drop_table('donation')
    # ### end Alembic commands ###
