"""empty message

Revision ID: c17f2e28c2f6
Revises: 1c45916ce45d
Create Date: 2024-01-19 10:59:09.055790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17f2e28c2f6'
down_revision = '1c45916ce45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_registration',
    sa.Column('reg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('break_id', sa.Integer(), nullable=True),
    sa.Column('datereg', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['break_id'], ['breakout.break_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_registration')
    # ### end Alembic commands ###
